"use client";

import { useMemo, useState, useTransition } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { DEFAULT_AGENT_TASKS, type AgentTask, type ForgeRequestPayload, type ForgeResponse, type AgentKey } from "@/lib/utils";
import { ForgeForm } from "@/components/forge/forge-form";
import { ForgeOutput } from "@/components/forge/forge-output";
import { AgentProgress } from "@/components/forge/agent-progress";

export const ForgeWorkspace = () => {
  const [tasks, setTasks] = useState<AgentTask[]>(DEFAULT_AGENT_TASKS);
  const [result, setResult] = useState<ForgeResponse | null>(null);
  const [activeTask, setActiveTask] = useState<AgentKey | null>(null);
  const [isPending, startTransition] = useTransition();
  const [error, setError] = useState<string | null>(null);

  const resetTasks = () => {
    setTasks(DEFAULT_AGENT_TASKS.map((task) => ({ ...task })));
  };

  const updateTask = (id: AgentKey, updates: Partial<AgentTask>) => {
    setTasks((prev) =>
      prev.map((task) => (task.id === id ? { ...task, ...updates } : task)),
    );
  };

  const simulateProgress = () => {
    const sequence: AgentKey[] = [
      "architect",
      "copywriter",
      "visual",
      "integration",
    ];

    let delay = 0;
    sequence.forEach((id, index) => {
      setTimeout(() => {
        setActiveTask(id);
        updateTask(id, { status: "running" });
      }, delay);

      setTimeout(() => {
        updateTask(id, {
          status: "success",
          output: index === 0 ? "Blueprint generated" : undefined,
        });
        setActiveTask(index < sequence.length - 1 ? sequence[index + 1] : null);
      }, (delay += 1200));
    });
  };

  const handleSubmit = async (payload: ForgeRequestPayload) => {
    startTransition(async () => {
      setError(null);
      setResult(null);
      resetTasks();
      simulateProgress();

      try {
        const response = await fetch("/api/forge", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify(payload),
        });

        const data = await response.json();
        if (!data.success) {
          throw new Error(data.error ?? "Forge pipeline failed");
        }

        setResult(data.result as ForgeResponse);
        const agentOrder: AgentKey[] = [
          "architect",
          "copywriter",
          "visual",
          "integration",
        ];
        agentOrder.forEach((agentKey) => {
          updateTask(agentKey, {
            status: "success",
            output: JSON.stringify((data.result as ForgeResponse)[agentKey], null, 2),
          });
        });
        setActiveTask(null);
      } catch (err) {
        setError(
          err instanceof Error ? err.message : "Unable to run forge pipeline",
        );
        setActiveTask(null);
      }
    });
  };

  const autoGenerated = useMemo(() => result !== null, [result]);

  return (
    <div className="grid gap-10 lg:grid-cols-[420px_minmax(0,1fr)] xl:grid-cols-[440px_minmax(0,1fr)]">
      <div className="space-y-6">
        <ForgeForm onSubmit={handleSubmit} loading={isPending} />
        <div className="rounded-3xl border border-slate-800/60 bg-slate-950/50 p-6 text-sm text-slate-400">
          <p className="text-slate-100">Forge Insights</p>
          <ul className="mt-3 space-y-2">
            <li>• Multi-agent outputs stored in Supabase `forge_runs` table.</li>
            <li>• Stripe integration auto-creates priced subscriptions.</li>
            <li>• Booking and contact flows wire into Next.js App Router.</li>
            <li>• Deploy-ready for Vercel with environment templating.</li>
          </ul>
        </div>
      </div>
      <div className="relative space-y-6">
        <AnimatePresence>
          {error && (
            <motion.div
              initial={{ opacity: 0, y: -8 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -8 }}
              className="rounded-2xl border border-rose-500/50 bg-rose-500/10 p-4 text-sm text-rose-100"
            >
              {error}
            </motion.div>
          )}
        </AnimatePresence>
        <AgentProgress tasks={tasks} activeTask={activeTask} />
        <ForgeOutput result={result} />
        {autoGenerated ? null : (
          <motion.div
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            className="rounded-3xl border border-slate-800/60 bg-slate-950/40 p-6 text-sm text-slate-400"
          >
            <p className="font-semibold text-slate-100">Frontend Handoff</p>
            <p className="mt-2">
              Each Forge run synchronizes metadata, palette tokens, and hero
              imagery to Supabase Storage for downstream editing. Stripe product
              IDs hydrate your pricing components in real-time.
            </p>
          </motion.div>
        )}
      </div>
    </div>
  );
};
